In [ ]:
#Name : Tejas Narendra Patil 
# Id : 115351


In [2]:
import numpy as np

In [5]:
# 1. Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# 2. How to find the memory size of an array
memory_size = null_vector.nbytes
memory_size

80

In [7]:
# 3. Create a null vector of size 10 but the fifth value which is 1
null_vector_with_one = np.zeros(10)
null_vector_with_one[4] = 1

null_vector_with_one

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
# 4. Create a vector with values ranging from 15 to 45
vector_15_to_45 = np.arange(15, 46)
vector_15_to_45

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45])

In [9]:
# 5. Reverse a vector (The first element becomes last)
reversed_vector = vector_15_to_45[::-1]
reversed_vector

array([45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29,
       28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15])

In [12]:
# 6. Write a NumPy program to add, subtract, multiply, divide arguments element-wise
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
add = np.add(x, y)
subtract = np.subtract(x, y)
multiply = np.multiply(x, y)
divide = np.divide(x, y)

print(divide, multiply, subtract)

[0.2   0.333 0.429 0.5  ] [ 5 12 21 32] [-4 -4 -4 -4]


In [13]:
# 7. Write a NumPy program to round elements of the array to the nearest integer
rounded_array = np.round(divide)
rounded_array

array([0., 0., 0., 0.])

In [14]:
# 8. Write a NumPy program to get the floor and ceiling values of the elements of a NumPy array
floor_values = np.floor(divide)
ceiling_values = np.ceil(divide)
print(floor_values,ceiling_values)

[0. 0. 0. 0.] [1. 1. 1. 1.]


In [20]:
# 9. Write a NumPy program to calculate mean across dimensions, in a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean_across_dimensions = np.mean(array_2d, axis=0)
array_2d
mean_across_dimensions

array([4., 5., 6.])

In [21]:
# 10. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.
degrees_array = np.array([0, 30, 45, 60, 90])
radians_array = np.radians(degrees_array)
print(degrees_array, radians_array)

[ 0 30 45 60 90] [0.    0.524 0.785 1.047 1.571]


In [22]:
# 11. What is the use of all and any function in numpy?
# all: Tests whether all array elements along a given axis evaluate to True.
# any: Tests whether any array element along a given axis evaluates to True.


In [23]:
# 12. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
matrix_3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# 13. How to reverse the columns of a 2D array?
reversed_columns = matrix_3x3[:, ::-1]
reversed_columns

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [25]:
# 14. How to reverse the rows of a 2D array?
reversed_rows = matrix_3x3[::-1]
reversed_rows

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [27]:
# 15. Find indices of non-zero elements from [1,2,0,0,4,0]
non_zero_indices = np.nonzero([1, 2, 0, 0, 4, 0])
non_zero_indices

(array([0, 1, 4], dtype=int64),)

In [28]:
# 16. Write a NumPy program to compute the determinant of an array.
determinant = np.linalg.det(matrix_3x3)
determinant


0.0

In [29]:
# 17. Write a NumPy program to compute the inverse of a given matrix
inverse_matrix = np.linalg.inv(matrix_3x3 + np.eye(3))
inverse_matrix


array([[-2. , -1. ,  1. ],
       [-0.6,  0.6, -0.2],
       [ 1.8,  0.2, -0.4]])

In [30]:
# 18. Create a random vector of size 30 and find the mean value
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print(random_vector,mean_value)


[0.803 0.348 0.52  0.609 0.598 0.312 0.765 0.978 0.639 0.553 0.233 0.496
 0.745 0.759 0.762 0.92  0.085 0.668 0.826 0.849 0.934 0.825 0.986 0.41
 0.329 0.63  0.174 0.379 0.341 0.779] 0.6085486880646174


In [33]:
# 19. How to extract all numbers between a given range from a NumPy array?
array = np.arange(100)
extracted_numbers = array[(array >= 20) & (array <= 50)]
extracted_numbers

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [34]:
# 20. Create a 3x3x3 array with random values
random_3x3x3 = np.random.rand(3, 3, 3)
random_3x3x3

array([[[0.167, 0.303, 0.42 ],
        [0.452, 0.285, 0.549],
        [0.354, 0.412, 0.562]],

       [[0.191, 0.076, 0.241],
        [0.443, 0.126, 0.205],
        [0.382, 0.259, 0.773]],

       [[0.108, 0.638, 0.56 ],
        [0.14 , 0.942, 0.999],
        [0.531, 0.065, 0.746]]])

In [36]:
# 21. Create a 10x10 array with random values and find the minimum and max value
random_10x10 = np.random.rand(10, 10)
min_value = np.min(random_10x10)
max_value = np.max(random_10x10)
print(random_10x10)
print(min_value,max_value)

[[0.78  0.528 0.732 0.051 0.444 0.775 0.738 0.871 0.633 0.401]
 [0.516 0.392 0.141 0.66  0.987 0.949 0.346 0.437 0.101 0.847]
 [0.763 0.235 0.566 0.996 0.057 0.627 0.345 0.222 0.294 0.096]
 [0.077 0.913 0.701 0.4   0.722 0.091 0.435 0.193 0.387 0.428]
 [0.493 0.74  0.198 0.864 0.239 0.962 0.174 0.933 0.08  0.392]
 [0.239 0.355 0.29  0.053 0.047 0.505 0.361 0.816 0.382 0.725]
 [0.628 0.52  0.87  0.129 0.633 0.813 0.265 0.926 0.701 0.41 ]
 [0.131 0.843 0.497 0.086 0.428 0.829 0.811 0.767 0.547 0.254]
 [0.88  0.136 0.684 0.154 0.654 0.113 0.692 0.795 0.092 0.997]
 [0.654 0.438 0.499 0.447 0.259 0.337 0.97  0.259 0.32  0.377]]
0.04709371873138357 0.9971070575210196


In [37]:
# 22. Create a 2d array with 1 on the border and 0 inside
bordered_array = np.ones((10, 10))
bordered_array[1:-1, 1:-1] = 0
bordered_array

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
# 23. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix_with_diagonal = np.diag(1 + np.arange(4), k=-1)
matrix_with_diagonal


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [40]:
# 24. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# 25. Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
checkerboard_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [42]:
# 26. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
matrix_product = np.dot(matrix_5x3, matrix_3x2)
print(matrix_product)

[[0.989 0.321]
 [0.518 0.478]
 [0.976 0.26 ]
 [1.092 0.727]
 [0.913 0.442]]


In [43]:
# 27. Given a 1D array, negate all elements which are between 3 and 8, in place
array_1d = np.arange(10)
array_1d[(array_1d >= 3) & (array_1d <= 8)] *= -1
print(array_1d)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


In [44]:
# 28. How to round away from zero a float array?
float_array = np.array([-2.5, -1.6, 1.5, 2.6])
rounded_away_from_zero = np.copysign(np.ceil(np.abs(float_array)), float_array)
rounded_away_from_zero

array([-3., -2.,  2.,  3.])

In [46]:
# 29. How to find common values between the two arrays?
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 6, 7, 8, 9])
common_values = np.intersect1d(array1, array2)
common_values

array([5])

In [47]:
# 30. Create a vector of size 10 with values ranging from 0 to 1, both excluded
vector_0_to_1_excluded = np.linspace(0, 1, 12)[1:-1]
vector_0_to_1_excluded

array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

In [48]:
# 31. Create a random vector of size 10 and sort it
random_vector_10 = np.random.rand(10)
sorted_vector = np.sort(random_vector_10)
print(random_vector_10)
print(sorted_vector)

[0.774 0.55  0.588 0.994 0.326 0.899 0.171 0.065 0.575 0.034]
[0.034 0.065 0.171 0.326 0.55  0.575 0.588 0.774 0.899 0.994]


In [49]:
# 32. Create a 5x5 matrix with row values ranging from 0 to 4
matrix_5x5 = np.zeros((5, 5))
matrix_5x5 += np.arange(5)
print(matrix_5x5)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [50]:
# 33. Consider two random arrays A and B, check if they are equal
A = np.random.rand(10)
B = np.random.rand(10)
arrays_equal = np.array_equal(A, B)
arrays_equal

False

In [54]:
# 34. Create a random vector of size 10 and replace the maximum value by 0
random_vector_10_2 = np.random.rand(10)
random_vector_10_2[random_vector_10_2.argmax()] = 0
random_vector_10_2

array([0.408, 0.615, 0.387, 0.83 , 0.   , 0.572, 0.072, 0.482, 0.118,
       0.713])

In [55]:
# 35. How to find out multiple indices of an item?
array_with_duplicates = np.array([1, 2, 3, 4, 1, 2, 3, 4])
indices_of_item = np.where(array_with_duplicates == 1)
indices_of_item

(array([0, 4], dtype=int64),)

In [56]:
# 36. What is the equivalent of enumerate for NumPy arrays?
array_for_enumerate = np.array([10, 20, 30, 40])
enumerated_array = list(np.ndenumerate(array_for_enumerate))
enumerated_array


[((0,), 10), ((1,), 20), ((2,), 30), ((3,), 40)]

In [57]:
# 37. How to sort an array by the nth column?
unsorted_array = np.random.rand(5, 3)
sorted_by_nth_column = unsorted_array[unsorted_array[:, 1].argsort()]
sorted_by_nth_column

array([[0.483, 0.102, 0.839],
       [0.991, 0.212, 0.251],
       [0.775, 0.588, 0.837],
       [0.807, 0.916, 0.167],
       [0.305, 0.971, 0.519]])

In [62]:
# 38. How to swap two rows of an array?
array_to_swap_rows = np.arange(9).reshape(3, 3)
array_to_swap_rows[[0, 1]] = array_to_swap_rows[[1, 0]]
array_to_swap_rows

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [63]:
# 39. How to compute the mean of a NumPy array?
mean_of_array = np.mean(array_to_swap_rows)
mean_of_array

4.0

In [64]:
# 40. How to compute the median of a NumPy array?
median_of_array = np.median(array_to_swap_rows)
median_of_array

4.0

In [65]:
# 41. How to compute the standard deviation of a NumPy array?
std_of_array = np.std(array_to_swap_rows)
std_of_array

2.581988897471611

In [66]:
# 42. How to compute the mode of a NumPy array?
from scipy import stats
mode_of_array = stats.mode(array_to_swap_rows, axis=None)
mode_of_array


ModeResult(mode=0, count=1)

In [67]:
# 43. How to print only 3 decimal places in a python NumPy array?
np.set_printoptions(precision=3)
array_with_precision = np.random.rand(5)
array_with_precision

array([0.466, 0.56 , 0.826, 0.928, 0.085])

In [68]:
# 44. Write a NumPy program to compute the covariance matrix of two given arrays
array1 = np.random.rand(5)
array2 = np.random.rand(5)
covariance_matrix = np.cov(array1, array2)
covariance_matrix

array([[0.043, 0.049],
       [0.049, 0.073]])

In [69]:
# 45. How to find the most frequent value in a NumPy array?
array_with_frequencies = np.array([1, 2, 3, 1, 2, 1])
most_frequent_value = np.bincount(array_with_frequencies).argmax()
most_frequent_value

1

In [70]:
# 46. How to convert 1D array to 3D array?
array_1d_to_3d = np.arange(27).reshape(3, 3, 3)
array_1d_to_3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
# 47. How to convert 4D array to 2D array?
array_4d = np.arange(81).reshape(3, 3, 3, 3)
array_4d_to_2d = array_4d.reshape(9, 9)
array_4d_to_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [73]:
# 48. Create a Numpy array filled with all zeros
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [75]:
# 49. Find the number of rows and columns of a given matrix using NumPy
rows, columns = matrix_3x3.shape
print(rows,columns)

3 3
